name: unit-test
on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
jobs:   
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        working-directory: basics/web-project-01/
      - name: Run tests
        run: npm test
        working-directory: basics/web-project-01/
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        working-directory: basics/web-project-01/
      - name: Build
        run: npm run build
        working-directory: basics/web-project-01/
      - name: Deploy
        run: echo "Deploying..."
        

