name: Events Demo 1
# This workflow demonstrates advanced event filtering for pull_request and push events.
# It triggers on pull requests targeting specific branches and on pushes to the main branch with specific tags

# By default, pull request based on forks do not trigger workflows in the base repository for first time contributors. They need approval from maintainers.
# This is to protect your repo from getting spammed with unwanted workflows.
# We can add collaborators.

# By default, workflows get cancelled if Jobs fail and jobs fail when any step fails.

# We can skip workflow execution based on certain keywords on commit messages. e.g., [skip ci], [skip actions]
# git commit -m "Some changes [skip ci]"

on:
  pull_request:
    types:
      - opened
      # - synchronize these 3 are default types, when we do not pass any types
      # - reopened
    branches: # only trigger on PRs targeting these branches
      - main
      - 'feat/**' # matches 'feat/xyz', 'feat/abc/123'
      - 'dev-*' # matches 'dev-1', 'dev-feature'
  push: # All these filters performed as AND conditions
    branches:
      - main
    tags:
      - 'v*.*.*' # matches 'v1.0.0', 'v2.1.3', etc.
    paths:
      - 'basics/web-project-01/**' # only trigger if files in this path are changed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."